apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signalforge-agent.kubeconfigName" . }}
  labels:
    {{- include "signalforge-agent.labels" . | nindent 4 }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: in-cluster
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    contexts:
      - name: in-cluster
        context:
          cluster: in-cluster
          user: signalforge-agent
    {{- if ne (include "signalforge-agent.kubeContextAlias" .) "in-cluster" }}
      - name: {{ include "signalforge-agent.kubeContextAlias" . }}
        context:
          cluster: in-cluster
          user: signalforge-agent
    {{- end }}
    current-context: {{ include "signalforge-agent.kubeContextAlias" . }}
    users:
      - name: signalforge-agent
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
